### PR TITLE
add missing method

### PR DESCRIPTION
**Pull request by remicollet**
This allow to run unit test with PHPUnit 5.1

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: (too bad the interface changed in a minor version though)

**Comment by stof** [comment]
Yeah, too bad that PHPUnit does not follow semver...

**Comment by keradus** [comment]
maybe raise a bug for PHPUnit?

**Comment by keradus** [comment]
ref https://github.com/sebastianbergmann/phpunit/pull/1840#issuecomment-162552054

**Comment by keradus** [comment]
https://github.com/sebastianbergmann/phpunit/commit/073c4de6d013353df368ccb25f9de37f13f61d2d

**Comment by xabbuh** [comment]
So technically we do not need this change anymore, but maybe we should extend the `BaseTestListener` class so we (hopefully) do not have to change the code when PHPUnit 6 is released.

**Comment by nicolas-grekas** [comment]
we can't extend the BaseTestListener: we already extend TestSuite

**Comment by nicolas-grekas** [comment]
I'm :+1: for merging, planning for 6.0 compat

**Comment by xabbuh** [comment]
Oh indeed, then let's merge it as is. :+1:

**Comment by remicollet** [comment]
I confirm, this PR is no more required with PHPUnit 5.1.2.

**Comment by nicolas-grekas** [comment]
Closing until 6.0 is released, thank you @remicollet

**Pull request closed without merging**
