### PR TITLE
Fix compatibility with PHP <7.4

### PR DESCRIPTION
**Pull request by gmessier**
To fix issue #326

### CODE REVIEW

**Comment by derrabus** [comment]
The file you are fixing in meant for PHP 8.0 and above. It also contains union types that won't work on PHP 7.

**Comment by gmessier** [comment]
Oh. I didn't check things carefully.
In fact the problem is that we have this when we run Psalm:

"ERROR: ParseError - vendor/symfony/polyfill-mbstring/bootstrap80.php:125:86 - Syntax error, unexpected '=' on line 125 (see https://psalm.dev/173)
    function mb_scrub(string $string, string $encoding = null): string { $encoding ??= mb_internal_encoding(); return mb_convert_encoding($string, $encoding, $encoding); }"

**Comment by derrabus** [comment]
Closing then.

**Comment by gmessier** [comment]
But, we should still to find a way to prevent static analyzers to breaks because some files contains stuff that are not compatible with the PHP version used... manually add exclusions seems not the better way (not directly related to this package thought, but if you have ideas...).

**Comment by derrabus** [comment]
I suggest you open an issue for Psalm because that's where the issue is. This package needs to ship files for PHP 8 because the polyfilled extension behaves differently on PHP 8.

**Pull request closed without merging**
