### PR TITLE
Allow null in str_*() functions

### LINKED ISSUE #365: Parameter types of PHPH 8.0 str_*() functions too strict
Our polyfills of the `str_*()` functions introduced with PHP 8.0 seem to be a bit too strict about typing. Our version throws a `TypeError` when `null` is passed to them while PHP's own implementation treats `null` like an empty string.

https://3v4l.org/0VShO

This has caused some issues on Symfony after we have migrated to the polyfilled functions, for example symfony/symfony#42290

### PR DESCRIPTION
**Pull request by derrabus**
Fixes #365

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @derrabus.

**Comment by Tobion** [comment]
Passing null is deprecated in PHP 8.1. Doesn't this solution prevent people from seeing the deprecation when using the polyfill?
So I think the polyfill should also raise a deprecation in PHP 8.1.

**Comment by derrabus** [comment]
@Tobion The polyfilled code is never used on PHP 8.1 because PHP has native implementations of those functions since 8.0.

**Comment by Tobion** [comment]
Right... Was thinking these functions are like an extension that could be disabled.

**Pull request merged**
