### PR TITLE
Add root namespace to tune perf

### PR DESCRIPTION
**Pull request by nicolas-grekas**

### CODE REVIEW

**Comment by stof** [comment]
is PHP-CS-Fixer able to do it now ?

**Comment by nicolas-grekas** [comment]
@stof not to my knowledge unfortunately

**Comment by stof** [comment]
so you do it all by hand ?

**Comment by nicolas-grekas** [comment]
yes :)

**Comment by xabbuh** [comment]
@stof FriendsOfPHP/PHP-CS-Fixer#3223 is the PR implementing that feature

**Pull request merged**
