### PR TITLE
Fix Php80Test::testFdiv()

### PR DESCRIPTION
**Pull request by WinterSilence**
Need using `$this->assertEqualsWithDelta()` to compare float values.
Why not use `$this->assertEquals()` or `$this->assertSame()`? Because `(0.1 * 0.1) / 0.1` not equal 0.1, it's ~0.10000000000000002

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This reminds me https://github.com/symfony/symfony/pull/45475
This happens since https://github.com/sebastianbergmann/phpunit/pull/4874

/cc @sebastianbergmann is that legit?

**Comment by WinterSilence** [comment]
@nicolas-grekas your question to Sebastian is incorrect - this package use PhpUnit 5-6, https://github.com/sebastianbergmann/phpunit/pull/4874 is PhpUnit 8

**Review by derrabus — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
This PR is definitely motivated by https://github.com/sebastianbergmann/phpunit/pull/4874
The CI is currently green on versions that don't have that patch, and red on jobs that use recent PHP versions.

**Comment by nicolas-grekas** [comment]
Issue fixed in a932445
Thanks for submitting.

**Comment by WinterSilence** [comment]
@nicolas-grekas this PR motivated by https://github.com/symfony/polyfill/runs/5367868196?check_suite_focus=true
I'm don't see before #4874
It's not fixed it's f..n shame

**Comment by nicolas-grekas** [comment]
>  It's not fixed it's f..n shame

what do you mean? yes it is, see newest CI runs as a proof.

**Comment by WinterSilence** [comment]
@nicolas-grekas this PR too do this, but you close it and update test data instead using correct assertion.

**Comment by nicolas-grekas** [comment]
This PR works around the test data, which was wrong in the first place. We want an exact check, not an approximation here.

**Comment by WinterSilence** [comment]
@nicolas-grekas sorry, my fail

**Pull request closed without merging**
