### PR TITLE
Make the UUID polyfill compatible with PHP >=5.3.3

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @javiereguiluz.

**Comment by BackEndTea** [comment]
The uuid implementation uses `random_bytes`, which is only present in php 7+, or with the polyfill. So this project should then require the `random_compat` polyfill.

The reason the tests pass anyways is probably because one of the other polyfills has it as a dependency.

**Comment by lyrixx** [comment]
@BackEndTea It seems you are right. Would you mind submitting a PR for that ?

**Comment by BackEndTea** [comment]
@lyrixx I did in #207

**Pull request merged**
