### PR TITLE
fix function signature tests

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by stof** [comment]
IIRC, allowing `null` was done to allow compatibility with the coalescing mode of PHP's type, which allows `null` (but deprecated) until PHP 9 for native functions

**Comment by nicolas-grekas** [comment]
@stof is right

**Comment by xabbuh** [comment]
makes sense, I added two additional entries to the map to satisfy the tests instead

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
