### PR TITLE
Update branch-alias for 1.5

### PR DESCRIPTION
**Pull request by nicolas-grekas**

### CODE REVIEW

**Comment by stof** [comment]
@nicolas-grekas do you have a script to update this on symfony/polyfill and symfony/symfony, or is it just a search&replace on the project ?

**Comment by nicolas-grekas** [comment]
search-and-replace

**Comment by fabpot** [comment]
I have a script for symfony/symfony :)

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
